# Site settings
title: "Harsh Yadav"
description: "About Me"

# Base URL
baseurl: "" # leave empty for user site like yourusername.github.io

author: "Harsh Yadav"

# Optional settings
markdown: kramdown
